version: "3.2"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata: